# Generated by Django 2.2.28 on 2024-04-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0081_merge_20240313_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbycategory',
            name='name_ar',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hobbycategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hobbycategory',
            name='name_fi',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hobbycategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hobbycategory',
            name='name_sv',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hobbycategory',
            name='name_zh_hans',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
