# Generated by Django 2.2.28 on 2024-04-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0083_add_initial_data_to_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_html',
            field=models.TextField(blank=True, null=True, verbose_name='Html description'),
        ),
    ]
